// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SmartBin.Api.Data;

#nullable disable

namespace SmartBin.Api.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260305175227_addnull")]
    partial class addnull
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("SmartBin.Api.Models.Bin", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("IdentificationToken")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<float>("Latitude")
                        .HasColumnType("real");

                    b.Property<float>("Longitude")
                        .HasColumnType("real");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Bins");
                });

            modelBuilder.Entity("SmartBin.Api.Models.BinSection", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("BinId")
                        .HasColumnType("int");

                    b.Property<DateTime>("LastUpdated")
                        .HasColumnType("datetime2");

                    b.Property<float>("LevelPercentage")
                        .HasColumnType("real");

                    b.Property<int>("MaterialId")
                        .HasColumnType("int");

                    b.Property<float>("Weight")
                        .HasColumnType("real");

                    b.HasKey("Id");

                    b.HasIndex("BinId");

                    b.HasIndex("MaterialId");

                    b.ToTable("BinSections");
                });

            modelBuilder.Entity("SmartBin.Api.Models.CrowdDensity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<float>("AiConfidence")
                        .HasColumnType("real");

                    b.Property<int>("BinId")
                        .HasColumnType("int");

                    b.Property<string>("DensityLevel")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PeopleCount")
                        .HasColumnType("int");

                    b.Property<DateTime>("TimeStmp")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("BinId");

                    b.ToTable("CrowdDensities");
                });

            modelBuilder.Entity("SmartBin.Api.Models.Material", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Materials");
                });

            modelBuilder.Entity("SmartBin.Api.Models.SurroundingWaste", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<float>("AiConfidence")
                        .HasColumnType("real");

                    b.Property<int>("BinId")
                        .HasColumnType("int");

                    b.Property<int>("DetectedObjectsCount")
                        .HasColumnType("int");

                    b.Property<DateTime>("TimeStmp")
                        .HasColumnType("datetime2");

                    b.Property<string>("WasteLevel")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("BinId");

                    b.ToTable("SurroundingWastes");
                });

            modelBuilder.Entity("SmartBin.Api.Models.Transection", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<float?>("AiConfidence")
                        .HasColumnType("real");

                    b.Property<int>("BinId")
                        .HasColumnType("int");

                    b.Property<int>("MaterialId")
                        .HasColumnType("int");

                    b.Property<DateTime>("TimeStmp")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("BinId");

                    b.HasIndex("MaterialId");

                    b.ToTable("Transections");
                });

            modelBuilder.Entity("SmartBin.Api.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AuthToken")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("SmartBin.Api.Models.Bin", b =>
                {
                    b.HasOne("SmartBin.Api.Models.User", "User")
                        .WithMany("Bins")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("SmartBin.Api.Models.BinSection", b =>
                {
                    b.HasOne("SmartBin.Api.Models.Bin", "Bin")
                        .WithMany("BinSections")
                        .HasForeignKey("BinId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SmartBin.Api.Models.Material", "Materia")
                        .WithMany("BinSections")
                        .HasForeignKey("MaterialId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Bin");

                    b.Navigation("Materia");
                });

            modelBuilder.Entity("SmartBin.Api.Models.CrowdDensity", b =>
                {
                    b.HasOne("SmartBin.Api.Models.Bin", "Bin")
                        .WithMany()
                        .HasForeignKey("BinId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Bin");
                });

            modelBuilder.Entity("SmartBin.Api.Models.SurroundingWaste", b =>
                {
                    b.HasOne("SmartBin.Api.Models.Bin", "Bin")
                        .WithMany()
                        .HasForeignKey("BinId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Bin");
                });

            modelBuilder.Entity("SmartBin.Api.Models.Transection", b =>
                {
                    b.HasOne("SmartBin.Api.Models.Bin", "Bin")
                        .WithMany("Transections")
                        .HasForeignKey("BinId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SmartBin.Api.Models.Material", "Material")
                        .WithMany()
                        .HasForeignKey("MaterialId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Bin");

                    b.Navigation("Material");
                });

            modelBuilder.Entity("SmartBin.Api.Models.Bin", b =>
                {
                    b.Navigation("BinSections");

                    b.Navigation("Transections");
                });

            modelBuilder.Entity("SmartBin.Api.Models.Material", b =>
                {
                    b.Navigation("BinSections");
                });

            modelBuilder.Entity("SmartBin.Api.Models.User", b =>
                {
                    b.Navigation("Bins");
                });
#pragma warning restore 612, 618
        }
    }
}
